object test {
  def main(args: Array[String]): Unit = {
    val b = new BST()
    b.insert(new apple(30))
    b.insert(new grapes(50))
    b.insert(new papaya(15))
    b.insert(new cherry(20))
    b.insert(new grapes(10))
    b.insert(new gooseberries(40))
    b.insert(new mulberries(60))
    b.insert(new cherry(35))
    b.insert(new watermelon(90))
    b.insert(new raspberries(25))
    b.insert(new apple(75))
    b.insert(new pear(65))
    b.insert(new blueberries(45))
    b.insert(new avocado(80))
    println("-------- Test iterate --------")
    b.Iterate()
    println("------------------------------------")
    println("-------- test filter by type (Apple) --------")
    b.filterByType("Apple")
    println("------------------------------------")
    println("-------- test filter by weight (40) --------")
    b.filterByWeight(40)
    println("------------------------------------")
    println("-------- test find heaviest --------")
    b.printNode(b.findHeaviest().v)
    println("------------------------------------")
    println("-------- test find lightest --------")
    b.printNode(b.findLightest().v)
    println("------------------------------------")
    println("-------- Test magnify(Grapes,7) --------")
    b.magnifyByType("Grapes",7)
    b.Iterate()
    println("------------------------------------")

  }
}
